### ISSUE TITLE
Charts improvements and bug fixes

### ISSUE THREAD

**Issue by anuj-flipkart** [flipkart-incubator/varadhi#175]
PR changes:
- NPE fixes
- added JVM remote debug flags
- wget cert validation under flag for VPN issues (blocked in internal N/W)
- added values file for local setup

TODO:
- [ ] cleanup
- [ ] readme update
- [ ] remote args under flag

**Comment by gauravAshok** [comment]
added new fixes for charts:
https://github.com/flipkart-incubator/varadhi/pull/190
