### ISSUE TITLE
Create lean deployment for Varadhi

### ISSUE THREAD

**Issue by kmrdhruv** [flipkart-incubator/varadhi#24]
- This should keep authn/authz disabled (via config)
- Should create default org/project/team which allows users directly proceed with topic/subscriptions and produce/consume flows.

**Comment by sahil-chachan** [comment]
https://docs.google.com/document/d/1sEO1vEDMR8oeXsBigAAFFX6nUfXLDStdAIbeIf2Q7mo/edit#heading=h.mb10g6q7nqv5
