### ISSUE TITLE
Implement the produce layer benchmarking suite and run the benchmark.

### ISSUE THREAD

**Issue by kmrdhruv** [flipkart-incubator/varadhi#41]
This user story involves below tasks
- Define Criteria (# of topics with partitions, # of producers per topic, # grouped and ungrouped topics, Msg size, RPS per topic)
- Establish the produce layer overhead % (on top of the messaging stack).
- Establish horizontal scalability of produce layer i.e. system scales by adding more producers (assume no bottleneck at messaging tech stack)
- Scale test for 50K rps produce.
- Scale test for single topic with X partition for max throughput. 
- Suggest appropriate instance type (cpu vs memory vs n/w parameter) for few sample workloads

Sub-tasks
#105
#106
#107

**Comment by anuj-flipkart** [comment]
Create issue in https://github.com/flipkart-incubator/varadhi/issues/191
