### ISSUE TITLE
Add base interface for inter node coordination.

### ISSUE THREAD

**Issue by gauravAshok** [flipkart-incubator/varadhi#70]
Scope of this ticket is to implement the message channel for inter node interaction as suggested here - 

https://docs.google.com/document/d/1CPOPcM05TufnsXKoD0FrEqoXrH6xecVYk4NDkg4dFus/edit

Cluster membership is managed by alternate issue https://github.com/flipkart-incubator/varadhi/issues/84

**Comment by kmrdhruv** [comment]
1 pager detailing this task -- https://docs.google.com/document/d/1CPOPcM05TufnsXKoD0FrEqoXrH6xecVYk4NDkg4dFus/edit

**Comment by kmrdhruv** [comment]
This is covered by https://github.com/flipkart-incubator/varadhi/issues/84, which is already assigned for execution.
So closing this task.
